export interface studentType {
    "rollId": "clqc78h8h0001ufowovskgm0s",
    "username": "Ama",
    "firstName": "Ama",
    "lastName": "Ghana",
    "middleName": null,
    "email": "ama@gmail.com",
    "password": "$2a$10$JPZyS25RvUqD0AFGove/TeqK1ajc01EZRqSBrLIdsUuu8QZiMUvuy",
    "dateOfBirth": null,
    "contact": null,
    "gender": "female",
    "admissionDate": null,
    "religion": null,
    "nationality": null,
    "guardianName": "Philomena",
    "guardianNumber": null,
    "relationsToGuardian": null,
    "medicalConditions": null,
    "allergies": null,
    "photo": null,
    "previousSchool": null,
    "status": "active",
    "role": "student",
    "emergencyContact": null,
    "emergencyContactName": null,
    "createdAt": "2023-12-19T10:25:33.761Z",
    "updatedAt": "2023-12-19T10:25:33.761Z"
  }[]