import "./globals.css";
import { Inter } from "next/font/google";
import { Button, ConfigProvider, Space } from "antd";
import Providers from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <ConfigProvider
        theme={{
          token: {
            // Seed Token
            colorPrimary: "#A25800",
            borderRadius: 8,

            // Alias Token
            colorBgContainer: "#fff",
          },
        }}
      >
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ConfigProvider>
    </Providers>
  );
}
